# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMQwTUn1j2lgWLYVk224T9MY8JwnanXs

### Projeto de Calculadora:
"""

valor1 = input('Digite um numero: ')
valor2 = input('Digite outro numero:')

valor1 = int(valor1)
valor2 = int(valor2)

print('Escolha uma operação: \n','1 - Soma\n','2 - Subtração\n','3 - Multiplicação\n','4 - Divisão\n','5 - Potenciação\n','6 - Divisão Inteira\n','7 - Resto da Divisão\n')
operacao = input()

if operacao == '1':
    print(valor1 + valor2)
elif operacao == '2':
    print(valor1 - valor2)
elif operacao == '3':
    print(valor1 * valor2)
elif operacao == '4':
    print(valor1 / valor2)
elif operacao == '5':
    print(valor1 ** valor2)
elif operacao == '6':
    print(valor1 // valor2)
elif operacao == '7':
    print(valor1 % valor2)
else:
    print('Operação Inválida')